#[theme]
#base="light"
#primaryColor="#b37171"
#textColor="#1a1a20"
#font="serif"

[theme]
base = "light"
primaryColor = "#b37171"
textColor = "#1a1a20"
font = "serif"
secondaryBackgroundColor = "#c3c0c0"
